pipeline {
  environment {
    registry = "basicprojecttemplate/backend-springboot-images"
    registryCredential = 'basicprojecttemplate'
    dockerImage = ''
  }
  agent any
  stages {
     
    stage('Cloning Git') {
      steps {
        git 'https://github.com/basicprojecttemplate/backend-template.git'
      }
    }
    
    stage('Building image') {
      steps{
        script {
          dir('./spring-boot/springboot-backend-template') {
            dockerImage = docker.build registry + ":$BUILD_NUMBER"
          }
        }
      }
    }
    
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }
}
