pipeline {
  environment {
    registry = "basicprojecttemplate/backend-springboot-images"
    registryCredential = 'basicprojecttemplate'
    dockerImage = ''
  }
  agent any
  stages {
  
    stage('Cloning Git') {
      steps {
        git 'https://github.com/basicprojecttemplate/backend-template.git'
        sh """
        	echo "Vishwa -- Cloning Git"
			ls
			pwd
			ls -ltr
			hostname
		"""
      }
    }
    
    stage('Building image') {
      steps{
		sh """
			echo "Vishwa -- Building image stage->steps"
			ls
			pwd
			ls -ltr
			hostname
		"""
        script {
			sh """
				echo "Vishwa -- Building image stage->steps-> script"
				ls
				pwd
				ls -ltr
				hostname
			"""
          dir('./backend-template/spring-boot/springboot-backend-template') {
			sh """
				echo "Vishwa -- Building image stage->steps-> script->dir"
				ls
				pwd
				ls -ltr
				hostname
			"""
          	dockerImage = docker.build registry + ":$BUILD_NUMBER"
          }
        }
      }
    }
    
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }
}